/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Arrays;
import javax.swing.ImageIcon;
/**
 *
 * @author Yuvan
 */
public class C1234 extends javax.swing.JFrame {

    /**
     * Creates new form C1234
     */
    public C1234() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0,0,(int)dim.getWidth(), (int) dim.getHeight());
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/vshopping";
            System.out.println("success");
            Connection c = DriverManager.getConnection(url, "root" , "");
            Statement st = c.createStatement();
            //JOptionPane.showMessageDialog(null, "Connected successfully");
//            Statement st = c.createStatement();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Not connected");
            System.out.println("Exception"+e);
        }
        
        
        
    }
    public String PID;
    public String log;
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        logged = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 340, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 621, 180, 30));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 30, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.setRequestFocusEnabled(false);
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 423, 79, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Quantity :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 416, 89, 30));

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Buy Now");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 621, 180, 30));

        logged.setText("jLabel4");
        getContentPane().add(logged, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, 107, -1));

        jLabel5.setText("logged in as");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 68, -1));

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 127, 92, 37));

        price.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 182, 92, 34));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Price :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 182, 68, 34));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Product id :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 127, 100, 37));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 247, 301, 122));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Drescription :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 234, 126, 40));

        jLabel2.setText("1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hari\\Downloads\\My project-3.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -220, 1366, 1200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
            {
                System.out.println("success1");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vshopping","root","");
                Statement st = con.createStatement();
                Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/vshopping","root","");
                Statement stmt = con1.createStatement(ResultSet.TYPE_FORWARD_ONLY,ResultSet.CONCUR_READ_ONLY);     
                ResultSet  rs = stmt.executeQuery("select * FROM products");
                int a=(Integer) jSpinner1.getValue();
                System.out.println("success1");
                int i=0;
                while (rs.next()&&i==0)
                {
                    String str6=rs.getString("PID");
                    String str7=idLabel.getText();
                    if(str6.equals(str7))
                    {
                        int cost=rs.getInt("Price");
                        String str5=rs.getString("PName");
                        System.out.println(str5);
                        int b=a*cost;
                        String str1="Harry Potter";
                        String str2=this.logged.getText()+"cart";
                        String str3=this.logged.getText();
                        if(!str3.equals("guest"))
                        {
                        //int str6=rs.getInt("PID");
                        String str = "INSERT INTO cart values('"+str3+"','"+str6+"','"+str5+"',"+cost+","+a+","+b+")";
                        System.out.println("success1");
                        st.executeUpdate(str);
                        System.out.println("success1");
                        i=1;
                        JOptionPane.showMessageDialog(null,"Added to Cart");
                        }
                        else
                            JOptionPane.showMessageDialog(null,"Sign up to Buy");
                            
                        
                    }
                    
                       
                }
                
                //JOptionPane.showMessageDialog(null,"Inserted");
                System.out.println("success2");
                
                rs.close();
                stmt.close();
                con.close();
                st.close();
                con1.close();
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,"Not Inserted");
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PostPage s1=new PostPage();
        s1.logged.setText(this.logged.getText());
        s1.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try
            {
                System.out.println("success1");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vshopping","root","");
                Statement st = con.createStatement();
                Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/vshopping","root","");
                Statement stmt = con1.createStatement(ResultSet.TYPE_FORWARD_ONLY,ResultSet.CONCUR_READ_ONLY);     
                ResultSet  rs = stmt.executeQuery("select * FROM products");
                int a=(Integer) jSpinner1.getValue();
                System.out.println("success1");
                int i=0;
                while (rs.next()&&i==0)
                {
                    String str6=rs.getString("PID");
                    String str7=idLabel.getText();
                    if(str6.equals(str7))
                    {
                        int cost=rs.getInt("Price");
                        String str5=rs.getString("PName");
                        System.out.println(str5);
                        int b=a*cost;
                        String str1="Harry Potter";
                        String str2=this.logged.getText()+"orders";
                        String str3=this.logged.getText();
                        if(str3!="guest")
                        {
                        //int str6=rs.getInt("PID");
                        String str = "INSERT INTO orders values('"+str3+"','"+str6+"','"+str5+"',"+cost+","+a+","+b+")";
                        System.out.println("success1");
                        st.executeUpdate(str);
                        System.out.println("success1");
                        i=1;
                        JOptionPane.showMessageDialog(null,"Your order is taken Thank You");
                        }
                        else
                            JOptionPane.showMessageDialog(null,"Sign up to Buy");
                            
                        
                    }
                    
                       
                }
                
                //JOptionPane.showMessageDialog(null,"Inserted");
                System.out.println("success2");
                
                rs.close();
                stmt.close();
                con.close();
                st.close();
                con1.close();
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,"Not Inserted");
            }
        

    }//GEN-LAST:event_jButton4ActionPerformed
    public void display()
    {
        try 
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vshopping","root","");
            Statement stmt = con.createStatement(ResultSet.TYPE_FORWARD_ONLY,ResultSet.CONCUR_READ_ONLY);     
            ResultSet  rs = stmt.executeQuery("select * FROM products");
            String str1 =PID;
            while(rs.next())
            {
                if(str1.equals(rs.getString("PID")))
                {
                       jLabel1.setText(rs.getString("PName"));
                       price.setText(rs.getString("Price"));
                       jTextArea1.setText(rs.getString("Description"));
                       jTextArea1.setEditable(false);
                       idLabel.setText(PID);
                       byte[]img = rs.getBytes("Image");
                       ImageIcon ic = new ImageIcon();
                       ic = new ImageIcon(img);
                       Image i1 = ic.getImage();
                       Image i2 = i1.getScaledInstance(500, 500, Image.SCALE_SMOOTH);
                       jLabel2.setIcon(new ImageIcon(i2));
                }
                
            }
            rs.close();
            stmt.close();
            con.close();
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C1234.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C1234.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C1234.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C1234.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
        
                new C1234().setVisible(true);
                //new C1234().display();
            
        
    
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel logged;
    private javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables
}
