
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nithi
 */
public class CreateEvent extends javax.swing.JFrame {
        String path = null;
        File f = null;
        private ImageIcon format = null;
        String fname = null;
        int s = 0;
        byte[] pimage = null;
    /**
     * Creates new form AddProduct
     */
    public CreateEvent() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0,0,(int)dim.getWidth(), (int) dim.getHeight());
        Connect();
    }
    Connection con;
    PreparedStatement pst;
     public String log;
//    ResultSet rs;
    public void Connect()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/helpingHandsDb";
            con = DriverManager.getConnection(url, "root" , "");
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null , "Not Connected");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pPrice = new javax.swing.JTextField();
        pName = new javax.swing.JTextField();
        pCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pDescription = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        imagePath = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("location");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 234, 194, 66));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Description");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 349, 194, 66));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Event Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 6, 194, 66));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Event Code");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 111, 194, 66));

        pPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPriceActionPerformed(evt);
            }
        });
        getContentPane().add(pPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 234, 254, 66));

        pName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(pName, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 6, 254, 66));

        pCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(pCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 122, 254, 66));

        pDescription.setColumns(20);
        pDescription.setRows(5);
        jScrollPane1.setViewportView(pDescription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 349, 368, 149));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton1.setText("Browse...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 538, 121, 45));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Event Image");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 526, 194, 66));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 603, 221, 69));
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 234, 392, 300));

        imagePath.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        imagePath.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(imagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 598, 553, 74));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1142, 20, 186, 52));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hari\\Downloads\\My project.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -220, 1366, 1200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pPriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String str = null;
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter ext = new FileNameExtensionFilter("PNG JPG AND JPEG" , "png" , "jpg" , "jpeg");
        jf.addChoosableFileFilter(ext);
        int n = jf.showOpenDialog(null);
        
        if(n == jf.APPROVE_OPTION)
            f = jf.getSelectedFile();
        
        path = f.getAbsolutePath();
        imagePath.setText(path);
        ImageIcon ic = new ImageIcon(path);
        Image img = ic.getImage().getScaledInstance(300,300,Image.SCALE_SMOOTH);
        image.setIcon(new ImageIcon(img));
/*        ChooseProductImage c = new ChooseProductImage();
        c.setVisible(true);
        this.setVisible(false);*/
/*        JFileChooser jf = new JFileChooser();
        int num = jf.showOpenDialog(null);
        System.out.println(num);
        System.out.println(JFileChooser.APPROVE_OPTION);
        String fileLoc = jf.getSelectedFile().getAbsolutePath();
        System.out.println(fileLoc);
            File fl = new File();*/
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Image Path = " + path);
        //System.out.println("Image Name : "+f.getName());
        //File f = new File(path);
        try
        {
            File f = new File(path);
            InputStream is = new FileInputStream(f);
            pst = con.prepareStatement("INSERT INTO event(Ename,EID,Location,Description,Image,Helper)VALUES(?,?,?,?,?,?)");
            pst.setString(2,pCode.getText());
            pst.setString(1,pName.getText());
            pst.setString(3,pPrice.getText());
            pst.setString(4, pDescription.getText());
            pst.setBlob(5,is);
            pst.setString(6, log);
            int inserted = pst.executeUpdate();
            if(inserted > 0)
                JOptionPane.showMessageDialog(null , "Product Added Successfully");
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null , "Enter details correctly");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       HelperHome o1=new HelperHome();
        
        o1.logged.setText(this.log);
        o1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductTemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel imagePath;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pCode;
    private javax.swing.JTextArea pDescription;
    private javax.swing.JTextField pName;
    private javax.swing.JTextField pPrice;
    // End of variables declaration//GEN-END:variables
}
