
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nithi
 */


public class RemoveAccount1 extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    /**
     * Creates new form RemoveAccount
     */
    public RemoveAccount1() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0,0,(int)dim.getWidth(), (int) dim.getHeight());
        Connect();
        FetchData();
    }
    public void Connect()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/helpingHandsDb";
            con = DriverManager.getConnection(url, "root" , "");
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null , "Not Connected");
        }
    }  
    
    public void FetchData()
    {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/helpingHandsDb";
                Connection c = DriverManager.getConnection(url, "root" , "");
                Statement st = c.createStatement();
                String query = "SELECT * FROM logindetails";
                ResultSet rs = st.executeQuery(query);
                ResultSetMetaData rm = rs.getMetaData();
                DefaultTableModel model = (DefaultTableModel)data.getModel();
                
                int cols = rm.getColumnCount();
                String[] colName = new String[cols];
                for(int i=0; i<cols; i++)
                        colName[i] = rm.getColumnName(i+1);
                model.setColumnIdentifiers(colName);
                data.setShowHorizontalLines(true);
                data.setShowVerticalLines(true);
                data.setRowHeight(30);
                data.getColumnModel().getColumn(2).setPreferredWidth(150);
                
                String fn , ln , email , pwd , city , state , mno , gender;
                while(rs.next())
                {
                    fn = rs.getString(1);
                    ln = rs.getString(2);
                    email = rs.getString(3);
                    pwd = rs.getString(4);
                    city = rs.getString(5);
                    state = rs.getString(6);
                    mno = rs.getString(7);
                    gender = rs.getString(8);
                    String[] row = {fn,ln,email,pwd,city,state,mno,gender};
                    model.addRow(row);
                }
                st.close();
                c.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Enter valid Emailid");
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        deleteAccount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1163, 6, 178, 45));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Email ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, -1, 34));

        emailInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 327, 34));

        deleteAccount.setBackground(new java.awt.Color(255, 51, 51));
        deleteAccount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        deleteAccount.setText("Delete Account");
        deleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountActionPerformed(evt);
            }
        });
        getContentPane().add(deleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 650, 224, 41));

        data.setBackground(new java.awt.Color(0, 0, 0));
        data.setBorder(javax.swing.BorderFactory.createTitledBorder("USER ACCOUNT DETAILS"));
        data.setForeground(new java.awt.Color(255, 255, 204));
        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        data.setDragEnabled(true);
        data.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(data);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 66, 1340, 578));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(958, 6, 178, 45));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hari\\Downloads\\My project.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -220, 1366, 1200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountActionPerformed
        try 
        {
            pst = con.prepareStatement("DELETE FROM logindetails WHERE Email = '"+ emailInput.getText() + "'");
            int status = pst.executeUpdate();
            if(status>0)
                JOptionPane.showMessageDialog(null , "DELETED SUCCESSFULLY");
            else
                JOptionPane.showMessageDialog(null , "USER NOT FOUND");
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(RemoveAccount1.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null , "Enter valid Email id");
        }
    }//GEN-LAST:event_deleteAccountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DataDetailsTemp d2 = new DataDetailsTemp();
        d2.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        data.setModel(new DefaultTableModel());
        FetchData();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveAccount1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable data;
    private javax.swing.JButton deleteAccount;
    private javax.swing.JTextField emailInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
